Test display
blueskysolarracing/revolution pull request #19
Opened 2023-04-06 15:36 UTC by albert4750

Display first implementation done

TODO:
switch GPIO and SPI used by library
currently added ignore for the two library files but we should review whether or not thats ok

2023-04-08 08:22 UTC, AussieSeaweed requested changes
The logic is there, but this won't run as it stands. We can discuss tomorrow.

2023-04-08 08:22 UTC, AussieSeaweed commented on revolution/environment.py
> +    right_indicator_light_status: bool = False
Some of these attributes are already present.

2023-04-08 08:22 UTC, AussieSeaweed commented on revolution/st7565.py
> +from __future__ import print_function
Not necessary

2023-04-08 08:22 UTC, AussieSeaweed commented on revolution/st7565.py
> +        import RPi.GPIO as GPIO
We can't just import RPi like this. We are not using Raspberry Pi

2023-04-08 08:22 UTC, AussieSeaweed commented on revolution/xglcd_font.py
> +    def __load_xglcd_font(self, path):
This is crazy lol

2023-04-08 08:22 UTC, AussieSeaweed commented on revolution/display.py
> +    def startup(self) -> None:
Should be run as a separate thread. This was done in def setup in other ``Application``s.

2023-04-26 18:36 UTC, TristanRobitaille commented on revolution/environment.py
> +    motor_state: int = 0  # 0=OFF, 1=PEDAL, 2=CRUISE, 3=REGEN
Enum for this and the ones below would be more readable

2023-09-20 00:44 UTC, closed without merging